---
title: "IO Psychology Reddit Analysis"
author: "Richard"
date: "2023-04-11"
output: html_document
---

# Script Settings and Resources
```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(RedditExtractoR)
library(tm)
library(qdap)
library(textstem)
library(RWeka)
library(ldatuning)
library(topicmodels)
library(tidytext)
library(wordcloud)
library(psych)
```

# Data Import and Cleaning
```{r import}
# urls <- find_thread_urls(subreddit="iopsychology", period="year")
# content <- get_thread_content(urls$url)urls <- readRDS("../out/urls.RDS")
urls <- readRDS("../out/urls.RDS")
content <- readRDS("../out/content.RDS")

week12_tbl <- tibble(
  upvotes = content$threads$upvotes,
  title = urls$title,
)

io_corpus_original <- VCorpus(VectorSource(week12_tbl$title))
io_corpus <- io_corpus_original %>%
  tm_map(content_transformer(replace_abbreviation)) %>%
  tm_map(content_transformer(replace_contraction)) %>%
  tm_map(removeWords, "IO") %>%
  tm_map(content_transformer(str_to_lower)) %>%
  tm_map(removeWords, c(stopwords("en"), "riopsychology", "io psychology", "i-o", "i/o")) %>%
  tm_map(removeWords, "[^[:alnum: ]]") %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace) %>%
  tm_map(content_transformer(lemmatize_words))

compare_them <- function(corpus1, corpus2) {
  row <- sample(1:length(corpus1), 1)
  writeLines(paste(corpus1[[row]]$content, corpus2[[row]]$content, sep="\n"))
}
compare_them(io_corpus_original, io_corpus)

twogram <- function(x) { NGramTokenizer(x, Weka_control(min=1, max=2)) }

# 734/2, 734/3 - target N = 244-367
io_dtm <- DocumentTermMatrix(io_corpus, control=list(tokenizer=twogram))
io_slim_dtm <- removeSparseTerms(io_dtm, .996)
as_tibble(as.matrix(io_dtm)) %>% View
as_tibble(as.matrix(io_slim_dtm)) %>% View

tuning <- FindTopicsNumber(
  io_dtm,
  topics = seq(2,10,1),
  metrics = c("Griffiths2004","CaoJuan2009","Arun2010","Deveaud2014"),
  verbose = TRUE
)
FindTopicsNumber_plot(tuning)

lda_results <- LDA(io_dtm, 5)
lda_betas <- tidy(lda_results, matrix="beta")
lda_betas %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  arrange(topic, -beta) %>%
  View

lda_gammas <- tidy(lda_results, matrix="gamma")
lda_highest_gamma <- lda_gammas %>%
  group_by(document) %>%
  top_n(1, gamma) %>%
  slice(1) %>%
  ungroup %>%
  mutate(document = as.numeric(document)) %>%
  arrange(document)

topics_tbl <- tibble(
  doc_id = lda_highest_gamma$document,
  original = week12_tbl$title,
  topic = lda_highest_gamma$topic,
  probability = lda_highest_gamma$gamma
)

final_tbl <- bind_cols(
  topics_tbl,
  upvotes = content$threads$upvotes
)

foranalysis_tbl <- bind_cols(
  final_tbl,
  as_tibble(dummy.code(final_tbl$topic))
) %>%
  rename_with(~str_c("Topic_", .), `3`:`2`)

```


```{r visualization}
wordCounts <- colSums(as.matrix(io_slim_dtm))
wordNames <- io_slim_dtm$dimnames$Terms
wordcloud(wordNames, wordCounts, max.words=30)
```

```{r analysis}
model <- lm(upvotes ~ Topic_2 + Topic_3 + Topic_4 + Topic_5, data=foranalysis_tbl)
summary(model)
```